/**
 * Opinionated scaffolding templates for docker-compose.prod.yml and Dockerfile.
 *
 * Every template is pre-wired to the Traefik + shared-infra setup that the
 * deploy CLI's setup-server installs: two external networks (`traefik`, `shared`),
 * a Let's Encrypt resolver, TLS on 443, a shared Postgres and Redis living on
 * the `shared` network that apps reach via env vars.
 */

export interface ScaffoldContext {
  appName: string;          // e.g. "sample-app-staging"
  envName: string;          // e.g. "staging"
  gitRepo: string | null;   // e.g. "acme/sample-app"
  domain: string | null;    // e.g. "staging.example.com"
  appPort: number;          // e.g. 3000
  extraContainers: string;  // space-separated
}

export type TemplateKind =
  | "node-api"
  | "python-api"
  | "go-api"
  | "static-frontend"
  | "fullstack";

export interface TemplateOption {
  kind: TemplateKind;
  label: string;
  description: string;
  languageHint: string;
}

export const templates: TemplateOption[] = [
  { kind: "node-api", label: "Node.js API", description: "Express / Fastify / NestJS — JSON API on a port.", languageHint: "JavaScript / TypeScript" },
  { kind: "python-api", label: "Python API", description: "FastAPI / Flask / Django — served by uvicorn/gunicorn.", languageHint: "Python" },
  { kind: "go-api", label: "Go API", description: "net/http / chi / gin — compiled static binary.", languageHint: "Go" },
  { kind: "static-frontend", label: "Static frontend", description: "Vite / CRA / SvelteKit static — served by nginx.", languageHint: "nginx" },
  { kind: "fullstack", label: "Full-stack (frontend + backend)", description: "Separate containers for your API and web UI, behind one domain.", languageHint: "mixed" },
];

// ---------------------------------------------------------------------------
// docker-compose.prod.yml
// ---------------------------------------------------------------------------

function image(ctx: ScaffoldContext, suffix = ""): string {
  const repo = ctx.gitRepo ?? "your-org/your-repo";
  return `ghcr.io/${repo}${suffix}:${ctx.envName}`;
}

function routerBlock(appName: string, domain: string | null, port: number, svc = "app"): string {
  if (!domain) {
    // Without a domain we can't do host-based routing. Emit a comment so the
    // user knows to fill it in later.
    return `      # No domain configured — add Traefik labels here once you have one:
      # - "traefik.enable=true"
      # - "traefik.http.routers.${appName}.rule=Host(\`your-domain.example\`)"
      # - "traefik.http.routers.${appName}.entrypoints=websecure"
      # - "traefik.http.routers.${appName}.tls.certresolver=letsencrypt"
      # - "traefik.http.services.${appName}.loadbalancer.server.port=${port}"`;
  }
  const suffix = svc === "app" ? "" : "-" + svc;
  return `      - "traefik.enable=true"
      - "traefik.http.routers.${appName}${suffix}.rule=Host(\`${domain}\`)"
      - "traefik.http.routers.${appName}${suffix}.entrypoints=websecure"
      - "traefik.http.routers.${appName}${suffix}.tls=true"
      - "traefik.http.routers.${appName}${suffix}.tls.certresolver=letsencrypt"
      - "traefik.http.services.${appName}${suffix}.loadbalancer.server.port=${port}"`;
}

function baseService(ctx: ScaffoldContext, svc = "app", port = ctx.appPort): string {
  return `  ${svc}:
    image: ${image(ctx, svc === "app" ? "" : "-" + svc)}
    container_name: ${ctx.appName}-${svc}
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
      - shared-db
    labels:
${routerBlock(ctx.appName, ctx.domain, port, svc)}`;
}

export function generateCompose(kind: TemplateKind, ctx: ScaffoldContext): string {
  const header = `# Generated by Bishop for ${ctx.appName} (${ctx.envName}).
# This file is committed to your repo and scp'd to the server by ./deploy.
# Edit freely — Bishop will not overwrite without asking.

services:
`;
  const footer = `
networks:
  proxy:
    external: true
  shared-db:
    external: true
`;
  const extraNote = ctx.extraContainers.trim()
    ? `\n# Extra containers declared in .deploy/config: ${ctx.extraContainers}\n# Add them as additional services below, on the 'shared' network.\n`
    : "";

  switch (kind) {
    case "node-api":
    case "python-api":
    case "go-api":
      return header + baseService(ctx) + "\n" + extraNote + footer;

    case "static-frontend":
      // Nginx serves static assets on :80 inside the container; Traefik handles TLS.
      return header + baseService(ctx, "app", 80) + "\n" + extraNote + footer;

    case "fullstack": {
      // Two services: the API on <domain>/api and the web UI on <domain>/
      const apiDomain = ctx.domain ?? "example.com";
      const api = `  api:
    image: ${image(ctx, "-api")}
    container_name: ${ctx.appName}-api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy
      - shared-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ctx.appName}-api.rule=Host(\`${apiDomain}\`) && PathPrefix(\`/api\`)"
      - "traefik.http.routers.${ctx.appName}-api.entrypoints=websecure"
      - "traefik.http.routers.${ctx.appName}-api.tls=true"
      - "traefik.http.routers.${ctx.appName}-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.${ctx.appName}-api.loadbalancer.server.port=${ctx.appPort}"
`;
      const web = `  web:
    image: ${image(ctx, "-web")}
    container_name: ${ctx.appName}-web
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${ctx.appName}-web.rule=Host(\`${apiDomain}\`)"
      - "traefik.http.routers.${ctx.appName}-web.entrypoints=websecure"
      - "traefik.http.routers.${ctx.appName}-web.tls=true"
      - "traefik.http.routers.${ctx.appName}-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.${ctx.appName}-web.loadbalancer.server.port=80"
`;
      return header + api + "\n" + web + extraNote + footer;
    }
  }
}

// ---------------------------------------------------------------------------
// Dockerfile
// ---------------------------------------------------------------------------

export function generateDockerfile(kind: TemplateKind, ctx: ScaffoldContext): string {
  switch (kind) {
    case "node-api":
      return `# Generated by Bishop — Node.js API.
# Two-stage: install prod deps, then copy everything and run.

FROM node:20-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE ${ctx.appPort}
CMD ["node", "dist/server.js"]
`;

    case "python-api":
      return `# Generated by Bishop — Python API (uvicorn).
FROM python:3.12-slim

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends gcc \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE ${ctx.appPort}
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "${ctx.appPort}"]
`;

    case "go-api":
      return `# Generated by Bishop — Go API (compiled static binary).
FROM golang:1.23-alpine AS build
WORKDIR /src
COPY go.* ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-s -w' -o /out/app ./cmd/app

FROM gcr.io/distroless/static-debian12
COPY --from=build /out/app /app
EXPOSE ${ctx.appPort}
ENTRYPOINT ["/app"]
`;

    case "static-frontend":
      return `# Generated by Bishop — static frontend served by nginx.
FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# If your build output is at /app/build (CRA) or /app/.svelte-kit/output/client,
# change the COPY above accordingly.
EXPOSE 80
`;

    case "fullstack":
      return `# Generated by Bishop — full-stack API half.
# For the frontend, add a second Dockerfile (e.g. web/Dockerfile) and update
# docker-compose.prod.yml to build it, or publish it to GHCR under
# ghcr.io/<org>/<repo>-web:${ctx.envName}.

FROM node:20-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-slim
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE ${ctx.appPort}
CMD ["node", "dist/server.js"]
`;
  }
}

// ---------------------------------------------------------------------------
// .dockerignore — keeps node_modules, .env, build output, etc. out of the image.
// ---------------------------------------------------------------------------

export function generateDockerignore(kind: TemplateKind): string {
  const common = `# Generated by Bishop.
node_modules
npm-debug.log
yarn-error.log
pnpm-debug.log

.git
.gitignore

.env
.env.*
!.env.example

.DS_Store
Thumbs.db

.vscode
.idea
*.swp
*.log

.deploy/cache
`;

  const extras: Record<TemplateKind, string> = {
    "node-api": "\n# Node build artifacts — rebuilt inside the image\ndist\nbuild\ncoverage\n.nyc_output\n",
    "python-api": "\n# Python build artifacts\n__pycache__\n*.pyc\n.venv\nvenv\n.pytest_cache\n.mypy_cache\n",
    "go-api": "\n# Go build artifacts\n/bin\n/vendor\n",
    "static-frontend": "\n# Frontend build artifacts — rebuilt inside the image\ndist\nbuild\n.next\n.nuxt\n.svelte-kit\n.cache\n",
    "fullstack": "\n# Build artifacts\ndist\nbuild\n.next\n.nuxt\n.svelte-kit\n",
  };

  return common + extras[kind];
}

// ---------------------------------------------------------------------------
// Shared infrastructure (Traefik + shared Postgres + shared Redis).
// These three files live under .deploy/infra/shared/ and the CLI scp's them
// to /opt/shared/ on every deploy. Identical across projects that share
// the same server. Edit only if you know what you're doing.
// ---------------------------------------------------------------------------

export function generateSharedCompose(): string {
  return `# Generated by Bishop — shared infrastructure.
# Runs Traefik (reverse proxy + TLS), shared Postgres, and shared Redis.
# Each deployed app reaches these via the 'shared-db' network.

services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    networks:
      - proxy

  shared-postgres:
    image: postgres:16
    container_name: shared-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${POSTGRES_ADMIN_USER}
      POSTGRES_PASSWORD: \${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - /mnt/data/shared/postgres:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh:ro
    networks:
      - shared-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  shared-redis:
    image: redis:7-alpine
    container_name: shared-redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "\${REDIS_PASSWORD}", "--appendonly", "yes"]
    volumes:
      - /mnt/data/shared/redis:/data
    networks:
      - shared-db

networks:
  proxy:
    external: true
  shared-db:
    external: true
`;
}

export function generateSharedTraefik(acmeEmail = "admin@example.com"): string {
  return `# Generated by Bishop — Traefik static config.
# Static config changes require a Traefik restart; routing labels on each
# app service (set in their docker-compose.prod.yml) are picked up dynamically.

api:
  dashboard: false

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
    network: proxy

certificatesResolvers:
  letsencrypt:
    acme:
      email: ${acmeEmail}
      storage: /acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}
`;
}

export function generateSharedInitDb(): string {
  return `#!/bin/bash
# Generated by Bishop — runs on first Postgres container init.
# Reads DATABASES env var (comma-separated) and creates each DB if absent.
# Apps can set POSTGRES_ADMIN_* in /opt/shared/.env and use the superuser
# to create per-app roles, or request a database via DATABASES env var.

set -e

if [ -z "\${DATABASES:-}" ]; then
  echo "[init-databases] No DATABASES env var set — skipping per-app DB creation."
  exit 0
fi

IFS=',' read -ra DBS <<< "\$DATABASES"
for db in "\${DBS[@]}"; do
  db=$(echo "$db" | xargs)
  [ -z "$db" ] && continue
  echo "[init-databases] Ensuring database: $db"
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    SELECT 'CREATE DATABASE "$db"'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$db')\\gexec
EOSQL
done
`;
}
