//! Project initializer — GUI equivalent of `./deploy init`'s file-writing step.
//!
//! Writes `.deploy/config` (if absent) and `.deploy/remotes/<env>`. Does NOT do
//! server provisioning (Docker/Traefik/etc. install) — that's left to the CLI's
//! `setup-server` / `setup-app` commands, which remain the canonical installers.

use crate::config::project::load_project;
use crate::types::Project;
use serde::Deserialize;
use std::fs;
use std::path::PathBuf;

#[derive(Debug, Deserialize)]
pub struct InitInput {
    pub project_path: String,
    pub env_name: String,
    pub ssh_user: String,
    pub ssh_host: String,
    pub app_name: String,
    pub domain: Option<String>,
    pub app_port: Option<u16>,
    pub health_string: Option<String>,
    pub extra_containers: Option<String>,
    pub data_dirs: Option<String>,
    pub auto_secrets: Option<String>,
    pub domain_templates: Option<String>,
}

fn err<E: std::fmt::Display>(e: E) -> String { format!("{}", e) }

fn valid_env(name: &str) -> bool {
    !name.is_empty()
        && name.chars().next().map(|c| c.is_ascii_lowercase()).unwrap_or(false)
        && name.chars().all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

#[tauri::command]
pub fn init_project(input: InitInput) -> Result<Project, String> {
    if !valid_env(&input.env_name) {
        return Err("env name must be lowercase letters, digits, or hyphens; start with a letter".into());
    }
    if input.ssh_user.trim().is_empty() { return Err("ssh user required".into()); }
    if input.ssh_host.trim().is_empty() { return Err("ssh host required".into()); }
    if input.app_name.trim().is_empty() { return Err("app name required".into()); }

    let project_dir = PathBuf::from(&input.project_path);
    if !project_dir.is_dir() {
        return Err(format!("not a directory: {}", project_dir.display()));
    }

    let deploy_dir = project_dir.join(".deploy");
    fs::create_dir_all(deploy_dir.join("remotes")).map_err(err)?;
    fs::create_dir_all(deploy_dir.join("cache")).map_err(err)?;
    fs::create_dir_all(deploy_dir.join("infra")).map_err(err)?;

    let config_path = deploy_dir.join("config");
    if !config_path.exists() {
        let config = format!(
            "# Generated by Bishop setup wizard\n\
             APP_PORT={}\n\
             HEALTH_CHECK_STRING=\"{}\"\n\
             # Extra containers to check (space-separated, besides ${{APP_NAME}}-app)\n\
             EXTRA_CONTAINERS=\"{}\"\n\
             # Data directories to create (relative to /mnt/data/apps/${{APP_NAME}}/)\n\
             DATA_DIRS=\"{}\"\n\
             # Secret keys to auto-generate in .env (space-separated)\n\
             AUTO_SECRETS=\"{}\"\n\
             # Domain-dependent values (KEY=template pairs, ${{DOMAIN}} is replaced)\n\
             DOMAIN_TEMPLATES=\"{}\"\n",
            input.app_port.unwrap_or(3000),
            input.health_string.as_deref().unwrap_or("ok"),
            input.extra_containers.as_deref().unwrap_or(""),
            input.data_dirs.as_deref().unwrap_or(""),
            input.auto_secrets.as_deref().unwrap_or(""),
            input.domain_templates.as_deref().unwrap_or(""),
        );
        fs::write(&config_path, config).map_err(err)?;
    }

    // Remote file format: user@host:app-name.domain (domain may be empty).
    let app_part = match input.domain.as_deref() {
        Some(d) if !d.is_empty() => format!("{}.{}", input.app_name, d),
        _ => input.app_name.clone(),
    };
    let remote_content = format!("{}@{}:{}\n", input.ssh_user, input.ssh_host, app_part);
    let remote_path = deploy_dir.join("remotes").join(&input.env_name);
    fs::write(&remote_path, remote_content).map_err(err)?;

    load_project(&project_dir).map_err(|e| format!("{:#}", e))
}

#[derive(Debug, Deserialize)]
pub struct UpdateRemoteInput {
    pub project_path: String,
    pub env_name: String,
    pub ssh_user: String,
    pub ssh_host: String,
    pub app_name: String,
    pub domain: Option<String>,
}

#[tauri::command]
pub fn update_remote(input: UpdateRemoteInput) -> Result<Project, String> {
    if !valid_env(&input.env_name) {
        return Err("invalid env name".into());
    }
    let project_dir = PathBuf::from(&input.project_path);
    let remote_path = project_dir.join(".deploy").join("remotes").join(&input.env_name);
    if !remote_path.exists() {
        return Err(format!("remote '{}' does not exist", input.env_name));
    }
    let app_part = match input.domain.as_deref() {
        Some(d) if !d.is_empty() => format!("{}.{}", input.app_name, d),
        _ => input.app_name.clone(),
    };
    let content = format!("{}@{}:{}\n", input.ssh_user, input.ssh_host, app_part);
    fs::write(&remote_path, content).map_err(err)?;
    load_project(&project_dir).map_err(|e| format!("{:#}", e))
}
